apiVersion: v1beta3
kind: Pod
metadata:
  name: nfs-server
  labels:
    role: nfs-server
spec:
  containers:
    - name: nfs-server
      image: jsafrane/nfs-data
      privileged: true
      ports:
        - name: nfs
          containerPort: 2049
          protocol: tcp
