kind: Pod
apiVersion: v1beta3
metadata:
  name: mypod
spec:
  containers:
    - image: dockerfile/nginx
      name: myfrontend
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      source:
        persistentVolumeClaim:
         accessMode: ReadWriteOnce
         claimRef:
           name: myclaim-1
