apiVersion: v1beta1
desiredState:
  manifest:
    containers:
      - image: gcr.io/google_containers/pause
        name: testpd
        volumeMounts:
          - mountPath: "/testpd"
            name: "testpd"
    id: testpd
    version: v1beta1
    volumes:
      - name: testpd
        source:
          persistentDisk:
            # This GCE PD must already exist.
            pdName: "%insert_pd_name_here%"
            fsType: ext4
id: testpd
kind: Pod
labels:
  test: testpd
