apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: update-demo-kitten
spec:
  selector:
    name: update-demo
    version: kitten
  template:
    metadata:
      labels:
        name: update-demo
        version: kitten
    spec:
      containers:
      - image: kubernetes/update-demo:kitten
        name: update-demo
        ports:
        - containerPort: 80
          protocol: TCP
