apiVersion: v1beta3
kind: Service
metadata: 
  labels: 
    name: influxGrafana
  name: monitoring-influxdb-ui
spec: 
  ports:
    - port: 80
      targetPort: 8083
  selector: 
    name: influxGrafana


