apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/secret-volume/kube-ca
    server:  https://146.148.35.28
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes
current-context: kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:  
    auth-path: /etc/secret-volume/kube-auth-path
