apiVersion: v1beta1
kind: ReplicationController
id: monitoring-influx-grafana-controller
desiredState: 
  replicas: 1
  replicaSelector:
    name: influxGrafana
  podTemplate:
    labels:
      name: influxGrafana
      kubernetes.io/cluster-service: "true"
    desiredState:
      manifest:
        version: v1beta1
        id: monitoring-influx-grafana
        containers: 
          - name: influxdb
            image: gcr.io/google_containers/heapster_influxdb:v0.3
          - name: grafana
            image: gcr.io/google_containers/heapster_grafana:v0.6
            env: 
              - name: "INFLUXDB_EXTERNAL_URL"
                value: '/api/v1beta1/proxy/services/monitoring-grafana/db/'
              - name: "INFLUXDB_HOST"
                value: 'monitoring-influxdb'
              - name: "INFLUXDB_PORT"
                value: '80'
labels:
  name: influxGrafana
  kubernetes.io/cluster-service: "true"
