apiVersion: v1beta1
kind: ReplicationController
id: monitoring-influx-grafana-controller
desiredState: 
  replicas: 1
  replicaSelector:
    name: influxGrafana
  podTemplate:
    labels:
      name: influxGrafana
      kubernetes.io/cluster-service: "true"
    desiredState:
      manifest:
        version: v1beta1
        id: monitoring-influx-grafana
        containers: 
          - name: influxdb
            image: gcr.io/google-containers/heapster_influxdb:v0.3
            ports: 
              - containerPort: 8083
                hostPort: 8083
              - containerPort: 8086
                hostPort: 8086
          - name: grafana
            image: gcr.io/google-containers/heapster_grafana:v0.5
            env: 
              - name: "HTTP_USER"
                value: "admin"
              - name: "HTTP_PASS"
                value: "**None**"
              - name: "INFLUXDB_PROTO"
                value: "https"
              - name: "INFLUXDB_HOST"
                value: "localhost"
              - name: "INFLUXDB_PORT"
                value: ""
              - name: "KUBERNETES_API_PORT"
                value: ""
labels:
  name: influxGrafana
  kubernetes.io/cluster-service: "true"
