apiVersion: v1beta3
kind: ReplicationController
metadata: 
  labels: 
    name: influxGrafana
    kubernetes.io/cluster-service: "true"
  name: monitoring-influx-grafana-controller
spec: 
  replicas: 1
  selector: 
    name: influxGrafana
  template: 
    metadata: 
      labels: 
        name: influxGrafana
        kubernetes.io/cluster-service: "true"
    spec: 
      containers: 
        - image: gcr.io/google-containers/heapster_influxdb:v0.3
          name: influxdb
          ports: 
            - containerPort: 8083
              hostPort: 8083
            - containerPort: 8086
              hostPort: 8086
        - name: grafana
          image: gcr.io/google-containers/heapster_grafana:v0.5
          ports:
              - containerPort: 80
          env: 
            - name: "HTTP_USER"
              value: "admin"
            - name: "HTTP_PASS"
              value: "**None**"
            - name: "INFLUXDB_PROTO"
              value: "https"
            - name: "INFLUXDB_HOST"
              value: '"+window.location.hostname+"/api/v1beta1/proxy/services/monitoring-influxdb'
            - name: "INFLUXDB_PORT"
              value: ""
            - name: "KUBERNETES_API_PORT"
              value: ""
