apiVersion: v1beta1
namespace: rethinkdb
kind: ReplicationController
id: rethinkdb-rc-1.16.0
labels:
  db: rethinkdb
desiredState:
  replicas: 1
  replicaSelector:
    db: rethinkdb
    role: replicas
  podTemplate:
    labels:
      db: rethinkdb
      role: replicas
    desiredState:
      manifest:
        version: v1beta1
        id: rethinkdb
        containers:
          - name: rethinkdb
            image: antmanler/rethinkdb:1.16.0
            ports:
              - name: admin-port
                containerPort: 8080
              - name: driver-port
                containerPort: 28015
              - name: cluster-port
                containerPort: 29015
            volumeMounts:
                - name: rethinkdb-storage
                  mountPath: /data/rethinkdb_data
        volumes:
          - name: rethinkdb-storage
            source:
              emptyDir: {}
