apiVersion: v1beta3
kind: Service
metadata:
  labels:
    db: influxdb
  name: rethinkdb-admin
  namespace: rethinkdb
spec:
  ports:
   - port: 8080
     targetPort: 8080
  selector:
    db: rethinkdb
    role: admin
