apiVersion: v1beta3
kind: Service
metadata:
  labels:
    db: influxdb
  name: rethinkdb-driver
  namespace: rethinkdb
spec:
  ports:
    - port: 28015
      targetPort: 28015
  selector:
    db: rethinkdb
