apiVersion: v1beta3
kind: Pod
metadata:
  labels:
    db: rethinkdb
    role: admin
  name: rethinkdb-admin-1.16.0
  namespace: rethinkdb
spec:
  containers:
  - image: antmanler/rethinkdb:1.16.0
    name: rethinkdb
    ports:
    - containerPort: 8080
      name: admin-port
    - containerPort: 28015
      name: driver-port
    - containerPort: 29015
      name: cluster-port
    volumeMounts:
    - mountPath: /data/rethinkdb_data
      name: rethinkdb-storage
  volumes:
  - name: rethinkdb-storage
    emptyDir: {}
