#!/bin/bash
# /etc/init.d/kube-scheduler
#
# Startup and stop for kube-scheduler
#
# chkconfig 2345 20 80
# description: Starts and stops kube-scheduler

. /etc/rc.d/init.d/functions

prog="scheduler"
prog_bin="/usr/bin/kube-scheduler"
scheduler_config="/etc/kubernetes/scheduler"
config="/etc/kubernetes/config"
desc="scheduler of kubernetes"


if ! [ -f $prog_bin ]; then
    echo "$prog_bin binary not found."
    exit 5
fi

if [ -f $scheduler_config ]; then
    . $scheduler_config
else
    echo "No scheduler config file found in /etc/kubernetes... exiting"
    exit 5STER
fi


if [ -f $config ]; then
    . $config
else
    echo "No kubernetes config file found in /etc/kubernetes... exiting"
    exit 5
fi

start() {
    echo "Starting $desc ($prog): "
    $prog_bin \
        ${KUBE_LOGTOSTDERR} \
        ${KUBE_LOG_LEVEL} \
        ${KUBE_MASTER} \
        ${KUBE_SCHEDULER_ARGS} >> /var/log/messages 2>&1 &
    RETVAL=$?
    return $RETVAL
}

stop() {
    echo "Shutting down $desc ($prog): "
    pkill -f $prog_bin
}

restart() {
    stop
    start
}

status() {
    if [ -z $pid ]; then
        pid=$(pgrep -f $prog_bin)
    fi

    if [ -z $pid ]; then
        echo "$prog is NOT running."
        return 1
    else
        echo "$prog is running (pid is $pid)"
    fi
}

case "$1" in
    start)   start;;
    stop)    stop;;
    restart) restart;;
    status)  status;;
    *)       echo "Usage: $0 {start|stop|restart|status}"
             RETVAL=2;;
esac
exit $RETVAL
