apiVersion: v1beta1
namespace: rethinkdb
kind: Pod
id: rethinkdb-admin-1.16.0
labels:
  db: rethinkdb
  role: admin
desiredState:
  manifest:
    version: v1beta1
    id: rethinkdb
    containers:
      - name: rethinkdb
        image: antmanler/rethinkdb:1.16.0
        ports:
          - name: admin-port
            containerPort: 8080
          - name: driver-port
            containerPort: 28015
          - name: cluster-port
            containerPort: 29015
        volumeMounts:
          - name: rethinkdb-storage
            mountPath: /data/rethinkdb_data
    volumes:
      - name: rethinkdb-storage
        source:
          emptyDir: {}
    restartPolicy:
      always: {}
