#
# This pod imports nfs-server.default.kube.local:/ into /var/www/html
#

apiVersion: v1beta3
kind: Pod
metadata:
  name: nfs-web
spec:
  containers:
    - name: web
      image: dockerfile/nginx
      ports:
        - name: web
          containerPort: 80
          protocol: tcp
      volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/var/www/html"
  volumes:
    - name: nfs
      nfs:
        # FIXME: use the right hostname
        server: nfs-server.default.kube.local
        path: "/"
        readOnly: false
