#!/bin/bash
# /etc/init.d/kube-proxy
#
# Startup script for kube-proxy
#
# chkconfig 2345 20 80
# description: Starts and stop kube-proxy

. /etc/init.d/functions

prog="kube-proxy"
prog_bin="/usr/bin/kube-proxy"
proxy_config="/etc/kubernetes/proxy"
config="/etc/kubernetes/config"
desc="minion of kubernetes proxy"

if ! [ -f $prog_bin ]; then
    echo "$prog_bin binary not found."
    exit 5
fi


if [ -f $proxy_config ]; then
    . $proxy_config
else
    echo "No proxy  config in /etc/kubernetes... exiting"
    exit 5
fi

if [ -f $config ]; then
    . $config
else
    echo "No kubernetes config in /etc/kubernetes... exiting"
    exit 5
fi

start() {
    echo "Starting $desc ($prog): "
    $prog_bin \
        ${KUBE_LOGTOSTDERR} \
        ${KUBE_LOG_LEVEL} \
        ${KUBE_MASTER} \
        ${KUBE_PROXY_ARGS} >> /var/log/messages 2>&1 &
    RETVAL=$?
    return $RETVAL
}

stop() {
    echo "Shutting down $desc ($prog): "
    pkill -f $prog_bin
}

restart() {
    stop
    start
}

status() {
    if [ -z $pid ]; then
        pid=$(pgrep -f $prog_bin)
    fi

    if [ -z $pid ]; then
        echo "$prog is NOT running."
        return 1
    else
        echo "$prog is running (pid is $pid)"
    fi
}

case "$1" in
    start)   start;;
    stop)    stop;;
    restart) restart;;
    status)  status;;
    *)       echo "Usage: $0 {start|stop|restart|status}"
             RETVAL=2;;
esac
exit $RETVAL
