#!/bin/bash
# /etc/init.d/kube-apiserver
#
# Startup script for kube-apiserver
#
# chkconfig: 2345 20 80
# description: Starts and stops kube-apiserver

. /etc/init.d/functions

prog="kube-apiserver"
prog_bin="/usr/bin/kube-apiserver"
apiserver_config="/etc/kubernetes/apiserver"
config="/etc/kubernetes/config"
desc="master of kubernetes api server"

if ! [ -f $prog_bin ]; then
	echo "$prog_bin binary not found."
	exit 5	
fi

if [ -f $apiserver_config ]; then
	. $apiserver_config
else
    echo "No apiserver config file found in /etc/kubernetes... exiting"
    exit 5
fi

if [ -f $config ]; then
    . $config
else
    echo "No kubernetes config file found in /etc/kubernetes... exiting"
    exit 5
fi

start() {
    echo "Starting $desc ($prog): "
    $prog_bin \
        ${KUBE_LOGTOSTDERR} \
        ${KUBE_LOG_LEVEL} \
        ${KUBE_ETCD_SERVERS} \
        ${KUBE_API_ADDRESS} \
        ${KUBE_API_PORT} \
        ${KUBELET_PORT} \
        ${KUBE_ALLOW_PRIV} \
        ${KUBE_SERVICE_ADDRESSES} \
        ${KUBE_API_ARGS} >> /var/log/messages 2>&1 &
    RETVAL=$?
    return $RETVAL
}

stop() {
    echo "Shutting down $desc ($prog): "
    pkill -f $prog_bin
}

restart() {
    stop
    start
}

status() {
    if [ -z $pid ]; then
        pid=$(pgrep -f $prog_bin)
    fi

    if [ -z $pid ]; then
        echo "$prog is NOT running."
        return 1
    else
        echo "$prog is running (pid is $pid)"
    fi
}

case "$1" in
    start)   start;;
    stop)    stop;;
    restart) restart;;
    status)  status;;
    *)       echo "Usage: $0 {start|stop|restart|status}"
             RETVAL=2;;
esac
exit $RETVAL

